### ISSUE TITLE
OperatorAPI 5xx response

### ISSUE THREAD

**Issue by VVX7** [preludeorg/operator-support#278]
OperatorAPI 5xx errors are returned as HTML.

Errors should be returned as JSON instead.

Steps to reproduce:
1. POST an Attack object containing a `null` value to /attack.

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>TypeError: Cannot convert undefined or null to object<br> &nbsp; &nbsp;at Function.keys (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at file:///tmp/.mount_preludX1smI6/resources/app.asar/static/js/objects/attack.js:93:16<br> &nbsp; &nbsp;at Array.forEach (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at validateTTP (file:///tmp/.mount_preludX1smI6/resources/app.asar/static/js/objects/attack.js:92:32)<br> &nbsp; &nbsp;at API_HANDLER.route.get.post.Object.assign.docstring (file:///tmp/.mount_preludX1smI6/resources/app.asar/static/js/api/handler.js:160:16)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/tmp/.mount_preludX1smI6/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/tmp/.mount_preludX1smI6/resources/app.asar/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at next (/tmp/.mount_preludX1smI6/resources/app.asar/node_modules/express/lib/router/route.js:131:14)<br> &nbsp; &nbsp;at Route.dispatch (/tmp/.mount_preludX1smI6/resources/app.asar/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/tmp/.mount_preludX1smI6/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)</pre>
</body>
</html>
```

**Comment by privateducky** [comment]
Will be patched in 1.1.
