### ISSUE TITLE
Forwarded ports from Operator -> Redirector can crash redirector

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#439]
1. Create new redirector
2. Go to account settings -> network -> set HTTP port to 8089
3. Connect to redirector via connect
4. run nmap -p 22,8089,2323 <redirector ip>

Crash

```javascript
node:buffer:734
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at Function.byteLength (node:buffer:734:11)
    at Protocol.forwardedTcpip (/snapshot/headless/node_modules/ssh2/lib/protocol/Protocol.js:1521:34)
    at openChannel (/snapshot/headless/node_modules/ssh2/lib/server.js:1347:22)
    at Client.forwardOut (/snapshot/headless/node_modules/ssh2/lib/server.js:1291:5)
    at Server.<anonymous> (/snapshot/headless/static/js/headless.js)
    at Server.emit (node:events:390:28)
    at TCP.onconnection (node:net:1577:8) {
  code: 'ERR_INVALID_ARG_TYPE'
} 
```

**Comment by privateducky** [comment]
@lzimm let's remember to circle on this topic when we're testing Connect for 1.5.
