### ISSUE TITLE
Enterprise Vectr plugin bug

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#554]
Report from enterprise user that Vectr publisher is using old (1.5) link format:
```
2022-06-16 20:33:01 - DEBUG (content.py:25 helper) {'event': '/publish'}
2022-06-16 20:33:01 - ERROR (base_events.py:1744 default_exception_handler) Task exception was never retrieved
future: <Task finished name='Task-85' coro=<Vectr.publish() done, defined at /home/ubuntu/outpost-master/app/publishers/impl/vectr.py:21> exception=KeyError('tactic')>
Traceback (most recent call last):
  File "/home/ubuntu/outpost-master/app/publishers/impl/vectr.py", line 23, in publish
    self._vectr.create_test_case(link=link_json, org_name=self._org_name, campaign_id=campaign_id)
  File "/home/ubuntu/outpost-master/app/publishers/impl/vectr.py", line 107, in create_test_case
    phase=self._normalize_phase(link['tactic']), technique=link['technique'], status="COMPLETED",
KeyError: 'tactic'
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:1015: InsecureRequestWarning: Unverified HTTPS request is being made to host 'http-inputs-dev-rz.splunkcloud.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
```

**Comment by privateducky** [comment]
We should get this in for the 1.7 release @makk94
